const GLOBAL_COUNTRIES: CountryConfig[] = [
  { code: "NG", name: "Nigeria", prefix: "+234", flag: "🇳🇬", region: "NG" },
  { code: "GB", name: "United Kingdom", prefix: "+44", flag: "🇬🇧", region: "GB" },
  { code: "US", name: "United States", prefix: "+1", flag: "🇺🇸", region: "US" },
  { code: "CA", name: "Canada", prefix: "+1", flag: "🇨🇦", region: "GLOBAL" },
  { code: "AU", name: "Australia", prefix: "+61", flag: "🇦", region: "GLOBAL" },
  { code: "DE", name: "Germany", prefix: "+49", flag: "🇩🇪", region: "GLOBAL" },
  { code: "FR", name: "France", prefix: "+33", flag: "🇫🇷", region: "GLOBAL" },
  { code: "ZA", name: "South Africa", prefix: "+27", flag: "🇿🇦", region: "GLOBAL" },
  { code: "GH", name: "Ghana", prefix: "+233", flag: "🇬", region: "GLOBAL" },
  { code: "KE", name: "Kenya", prefix: "+254", flag: "🇰🇪", region: "GLOBAL" },
  { code: "IN", name: "India", prefix: "+91", flag: "🇮🇳", region: "GLOBAL" },
  { code: "AE", name: "United Arab Emirates", prefix: "+971", flag: "🇦🇪", region: "GLOBAL" },
  { code: "IE", name: "Ireland", prefix: "+353", flag: "🇮", region: "GLOBAL" },
  { code: "IT", name: "Italy", prefix: "+39", flag: "🇮🇹", region: "GLOBAL" },
  { code: "ES", name: "Spain", prefix: "+34", flag: "🇪🇸", region: "GLOBAL" },
  { code: "PT", name: "Portugal", prefix: "+351", flag: "🇵🇹", region: "GLOBAL" },
  { code: "NL", name: "Netherlands", prefix: "+31", flag: "🇳", region: "GLOBAL" },
  { code: "BE", name: "Belgium", prefix: "+32", flag: "🇧🇪", region: "GLOBAL" },
  { code: "CH", name: "Switzerland", prefix: "+41", flag: "🇨🇭", region: "GLOBAL" },
  { code: "SE", name: "Sweden", prefix: "+46", flag: "🇸🇪", region: "GLOBAL" },
  { code: "NO", name: "Norway", prefix: "+47", flag: "🇳🇴", region: "GLOBAL" },
  { code: "DK", name: "Denmark", prefix: "+45", flag: "🇩🇰", region: "GLOBAL" },
  { code: "FI", name: "Finland", prefix: "+358", flag: "🇫🇮", region: "GLOBAL" },
  { code: "PL", name: "Poland", prefix: "+48", flag: "🇵🇱", region: "GLOBAL" },
  { code: "AT", name: "Austria", prefix: "+43", flag: "🇦🇹", region: "GLOBAL" },
  { code: "GR", name: "Greece", prefix: "+30", flag: "🇬🇷", region: "GLOBAL" },
  { code: "TR", name: "Turkey", prefix: "+90", flag: "🇹🇷", region: "GLOBAL" },
  { code: "UA", name: "Ukraine", prefix: "+380", flag: "🇺🇦", region: "GLOBAL" },
  { code: "CZ", name: "Czech Republic", prefix: "+420", flag: "🇨🇿", region: "GLOBAL" },
  { code: "RO", name: "Romania", prefix: "+40", flag: "🇷🇴", region: "GLOBAL" },
  { code: "HU", name: "Hungary", prefix: "+36", flag: "🇭🇺", region: "GLOBAL" },
  { code: "BR", name: "Brazil", prefix: "+55", flag: "🇧🇷", region: "GLOBAL" },
  { code: "MX", name: "Mexico", prefix: "+52", flag: "🇲🇽", region: "GLOBAL" },
  { code: "AR", name: "Argentina", prefix: "+54", flag: "🇦🇷", region: "GLOBAL" },
  { code: "CO", name: "Colombia", prefix: "+57", flag: "🇨🇴", region: "GLOBAL" },
  { code: "CL", name: "Chile", prefix: "+56", flag: "🇨🇱", region: "GLOBAL" },
  { code: "PE", name: "Peru", prefix: "+51", flag: "🇵🇪", region: "GLOBAL" },
  { code: "CN", name: "China", prefix: "+86", flag: "🇨🇳", region: "GLOBAL" },
  { code: "JP", name: "Japan", prefix: "+81", flag: "🇯🇵", region: "GLOBAL" },
  { code: "KR", name: "South Korea", prefix: "+82", flag: "🇰🇷", region: "GLOBAL" },
  { code: "SG", name: "Singapore", prefix: "+65", flag: "🇸🇬", region: "GLOBAL" },
  { code: "MY", name: "Malaysia", prefix: "+60", flag: "🇲🇾", region: "GLOBAL" },
  { code: "TH", name: "Thailand", prefix: "+66", flag: "🇹🇭", region: "GLOBAL" },
  { code: "PH", name: "Philippines", prefix: "+63", flag: "🇵🇭", region: "GLOBAL" },
  { code: "ID", name: "Indonesia", prefix: "+62", flag: "🇮🇩", region: "GLOBAL" },
  { code: "VN", name: "Vietnam", prefix: "+84", flag: "🇻🇳", region: "GLOBAL" },
  { code: "PK", name: "Pakistan", prefix: "+92", flag: "🇵🇰", region: "GLOBAL" },
  { code: "BD", name: "Bangladesh", prefix: "+880", flag: "🇧🇩", region: "GLOBAL" },
  { code: "SA", name: "Saudi Arabia", prefix: "+966", flag: "🇸🇦", region: "GLOBAL" },
  { code: "QA", name: "Qatar", prefix: "+974", flag: "🇶🇦", region: "GLOBAL" },
  { code: "KW", name: "Kuwait", prefix: "+965", flag: "🇰🇼", region: "GLOBAL" },
  { code: "EG", name: "Egypt", prefix: "+20", flag: "🇪🇬", region: "GLOBAL" },
  { code: "MA", name: "Morocco", prefix: "+212", flag: "🇲🇦", region: "GLOBAL" },
  { code: "DZ", name: "Algeria", prefix: "+213", flag: "🇩🇿", region: "GLOBAL" },
  { code: "TN", name: "Tunisia", prefix: "+216", flag: "🇹🇳", region: "GLOBAL" },
  { code: "ET", name: "Ethiopia", prefix: "+251", flag: "🇪", region: "GLOBAL" },
  { code: "TZ", name: "Tanzania", prefix: "+255", flag: "🇹🇿", region: "GLOBAL" },
  { code: "UG", name: "Uganda", prefix: "+256", flag: "🇺🇬", region: "GLOBAL" },
  { code: "RW", name: "Rwanda", prefix: "+250", flag: "🇷🇼", region: "GLOBAL" },
  { code: "CM", name: "Cameroon", prefix: "+237", flag: "🇨", region: "GLOBAL" },
  { code: "CI", name: "Ivory Coast", prefix: "+225", flag: "🇨🇮", region: "GLOBAL" },
  { code: "SN", name: "Senegal", prefix: "+221", flag: "🇸🇳", region: "GLOBAL" },
  { code: "ZM", name: "Zambia", prefix: "+260", flag: "🇿🇲", region: "GLOBAL" },
  { code: "ZW", name: "Zimbabwe", prefix: "+263", flag: "🇿🇼", region: "GLOBAL" },
  { code: "NZ", name: "New Zealand", prefix: "+64", flag: "🇳🇿", region: "GLOBAL" },
  { code: "IL", name: "Israel", prefix: "+972", flag: "🇮🇱", region: "GLOBAL" },
  { code: "JO", name: "Jordan", prefix: "+962", flag: "🇯🇴", region: "GLOBAL" },
  { code: "LB", name: "Lebanon", prefix: "+961", flag: "🇱🇧", region: "GLOBAL" },
];
