/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DramaRouteImport } from './routes/drama'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FollowersRouteImport } from './routes/followers'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LiveRouteImport } from './routes/live'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MusicRouteImport } from './routes/music'
import { Route as MusicPromotionGuideRouteImport } from './routes/music-promotion-guide'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QrRouteImport } from './routes/qr'
import { Route as ReportProblemRouteImport } from './routes/report-problem'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShortVideoPlatformForMusiciansRouteImport } from './routes/short-video-platform-for-musicians'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StemRouteImport } from './routes/stem'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminPayoutsRouteImport } from './routes/admin/payouts'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRevenueRouteImport } from './routes/admin/revenue'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminVerificationsRouteImport } from './routes/admin/verifications'
import { Route as ArtistOnboardingRouteImport } from './routes/artist.onboarding'
import { Route as ArtistStudioRouteImport } from './routes/artist.studio'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as HelpChatRouteImport } from './routes/help.chat'
import { Route as HelpSafetyRouteImport } from './routes/help.safety'
import { Route as InboxIdRouteImport } from './routes/inbox.$id'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileViewersRouteImport } from './routes/profile.viewers'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as StoryUserIdRouteImport } from './routes/story.$userId'
import { Route as StudioSectionRouteImport } from './routes/studio.$section'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as SettingsAccountVerificationRouteImport } from './routes/settings.account.verification'
import { Route as SettingsSecurityRecoveryRouteImport } from './routes/settings.security.recovery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DramaRoute = DramaRouteImport.update({
  id: '/drama',
  path: '/drama',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowersRoute = FollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicPromotionGuideRoute = MusicPromotionGuideRouteImport.update({
  id: '/music-promotion-guide',
  path: '/music-promotion-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportProblemRoute = ReportProblemRouteImport.update({
  id: '/report-problem',
  path: '/report-problem',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortVideoPlatformForMusiciansRoute =
  ShortVideoPlatformForMusiciansRouteImport.update({
    id: '/short-video-platform-for-musicians',
    path: '/short-video-platform-for-musicians',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StemRoute = StemRouteImport.update({
  id: '/stem',
  path: '/stem',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const ArtistOnboardingRoute = ArtistOnboardingRouteImport.update({
  id: '/artist/onboarding',
  path: '/artist/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistStudioRoute = ArtistStudioRouteImport.update({
  id: '/artist/studio',
  path: '/artist/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const HelpChatRoute = HelpChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => HelpRoute,
} as any)
const HelpSafetyRoute = HelpSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => HelpRoute,
} as any)
const InboxIdRoute = InboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InboxRoute,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LiveRoute,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileViewersRoute = ProfileViewersRouteImport.update({
  id: '/viewers',
  path: '/viewers',
  getParentRoute: () => ProfileRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const StoryUserIdRoute = StoryUserIdRouteImport.update({
  id: '/story/$userId',
  path: '/story/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSectionRoute = StudioSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => StudioRoute,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsAccountVerificationRoute =
  SettingsAccountVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => SettingsAccountRoute,
  } as any)
const SettingsSecurityRecoveryRoute =
  SettingsSecurityRecoveryRouteImport.update({
    id: '/recovery',
    path: '/recovery',
    getParentRoute: () => SettingsSecurityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/community': typeof CommunityRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/drama': typeof DramaRoute
  '/features': typeof FeaturesRoute
  '/followers': typeof FollowersRoute
  '/following': typeof FollowingRoute
  '/friends': typeof FriendsRoute
  '/help': typeof HelpRouteWithChildren
  '/inbox': typeof InboxRouteWithChildren
  '/live': typeof LiveRouteWithChildren
  '/mcp': typeof McpRoute
  '/music': typeof MusicRoute
  '/music-promotion-guide': typeof MusicPromotionGuideRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/profile': typeof ProfileRouteWithChildren
  '/qr': typeof QrRoute
  '/report-problem': typeof ReportProblemRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/short-video-platform-for-musicians': typeof ShortVideoPlatformForMusiciansRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stem': typeof StemRoute
  '/studio': typeof StudioRouteWithChildren
  '/trending': typeof TrendingRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/artist/onboarding': typeof ArtistOnboardingRoute
  '/artist/studio': typeof ArtistStudioRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/help/chat': typeof HelpChatRoute
  '/help/safety': typeof HelpSafetyRoute
  '/inbox/$id': typeof InboxIdRoute
  '/live/$id': typeof LiveIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/viewers': typeof ProfileViewersRoute
  '/settings/account': typeof SettingsAccountRouteWithChildren
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/security': typeof SettingsSecurityRouteWithChildren
  '/story/$userId': typeof StoryUserIdRoute
  '/studio/$section': typeof StudioSectionRoute
  '/u/$handle': typeof UHandleRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/settings/account/verification': typeof SettingsAccountVerificationRoute
  '/settings/security/recovery': typeof SettingsSecurityRecoveryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/community': typeof CommunityRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/drama': typeof DramaRoute
  '/features': typeof FeaturesRoute
  '/followers': typeof FollowersRoute
  '/following': typeof FollowingRoute
  '/friends': typeof FriendsRoute
  '/help': typeof HelpRouteWithChildren
  '/inbox': typeof InboxRouteWithChildren
  '/live': typeof LiveRouteWithChildren
  '/mcp': typeof McpRoute
  '/music': typeof MusicRoute
  '/music-promotion-guide': typeof MusicPromotionGuideRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/profile': typeof ProfileRouteWithChildren
  '/qr': typeof QrRoute
  '/report-problem': typeof ReportProblemRoute
  '/rewards': typeof RewardsRoute
  '/short-video-platform-for-musicians': typeof ShortVideoPlatformForMusiciansRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stem': typeof StemRoute
  '/studio': typeof StudioRouteWithChildren
  '/trending': typeof TrendingRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/artist/onboarding': typeof ArtistOnboardingRoute
  '/artist/studio': typeof ArtistStudioRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/help/chat': typeof HelpChatRoute
  '/help/safety': typeof HelpSafetyRoute
  '/inbox/$id': typeof InboxIdRoute
  '/live/$id': typeof LiveIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/viewers': typeof ProfileViewersRoute
  '/settings/account': typeof SettingsAccountRouteWithChildren
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/security': typeof SettingsSecurityRouteWithChildren
  '/story/$userId': typeof StoryUserIdRoute
  '/studio/$section': typeof StudioSectionRoute
  '/u/$handle': typeof UHandleRoute
  '/admin': typeof AdminIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/settings/account/verification': typeof SettingsAccountVerificationRoute
  '/settings/security/recovery': typeof SettingsSecurityRecoveryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/community': typeof CommunityRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/drama': typeof DramaRoute
  '/features': typeof FeaturesRoute
  '/followers': typeof FollowersRoute
  '/following': typeof FollowingRoute
  '/friends': typeof FriendsRoute
  '/help': typeof HelpRouteWithChildren
  '/inbox': typeof InboxRouteWithChildren
  '/live': typeof LiveRouteWithChildren
  '/mcp': typeof McpRoute
  '/music': typeof MusicRoute
  '/music-promotion-guide': typeof MusicPromotionGuideRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/profile': typeof ProfileRouteWithChildren
  '/qr': typeof QrRoute
  '/report-problem': typeof ReportProblemRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/short-video-platform-for-musicians': typeof ShortVideoPlatformForMusiciansRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stem': typeof StemRoute
  '/studio': typeof StudioRouteWithChildren
  '/trending': typeof TrendingRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/artist/onboarding': typeof ArtistOnboardingRoute
  '/artist/studio': typeof ArtistStudioRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/help/chat': typeof HelpChatRoute
  '/help/safety': typeof HelpSafetyRoute
  '/inbox/$id': typeof InboxIdRoute
  '/live/$id': typeof LiveIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/viewers': typeof ProfileViewersRoute
  '/settings/account': typeof SettingsAccountRouteWithChildren
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/security': typeof SettingsSecurityRouteWithChildren
  '/story/$userId': typeof StoryUserIdRoute
  '/studio/$section': typeof StudioSectionRoute
  '/u/$handle': typeof UHandleRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/settings/account/verification': typeof SettingsAccountVerificationRoute
  '/settings/security/recovery': typeof SettingsSecurityRecoveryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/community'
    | '/create'
    | '/discover'
    | '/drama'
    | '/features'
    | '/followers'
    | '/following'
    | '/friends'
    | '/help'
    | '/inbox'
    | '/live'
    | '/mcp'
    | '/music'
    | '/music-promotion-guide'
    | '/notifications'
    | '/offline'
    | '/profile'
    | '/qr'
    | '/report-problem'
    | '/rewards'
    | '/settings'
    | '/short-video-platform-for-musicians'
    | '/sitemap.xml'
    | '/stem'
    | '/studio'
    | '/trending'
    | '/verify'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/content'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/artist/onboarding'
    | '/artist/studio'
    | '/auth/callback'
    | '/help/chat'
    | '/help/safety'
    | '/inbox/$id'
    | '/live/$id'
    | '/posts/$id'
    | '/profile/edit'
    | '/profile/viewers'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/security'
    | '/story/$userId'
    | '/studio/$section'
    | '/u/$handle'
    | '/admin/'
    | '/settings/'
    | '/.mcp/invoke-tool/$tool'
    | '/settings/account/verification'
    | '/settings/security/recovery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community'
    | '/create'
    | '/discover'
    | '/drama'
    | '/features'
    | '/followers'
    | '/following'
    | '/friends'
    | '/help'
    | '/inbox'
    | '/live'
    | '/mcp'
    | '/music'
    | '/music-promotion-guide'
    | '/notifications'
    | '/offline'
    | '/profile'
    | '/qr'
    | '/report-problem'
    | '/rewards'
    | '/short-video-platform-for-musicians'
    | '/sitemap.xml'
    | '/stem'
    | '/studio'
    | '/trending'
    | '/verify'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/content'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/artist/onboarding'
    | '/artist/studio'
    | '/auth/callback'
    | '/help/chat'
    | '/help/safety'
    | '/inbox/$id'
    | '/live/$id'
    | '/posts/$id'
    | '/profile/edit'
    | '/profile/viewers'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/security'
    | '/story/$userId'
    | '/studio/$section'
    | '/u/$handle'
    | '/admin'
    | '/settings'
    | '/.mcp/invoke-tool/$tool'
    | '/settings/account/verification'
    | '/settings/security/recovery'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/community'
    | '/create'
    | '/discover'
    | '/drama'
    | '/features'
    | '/followers'
    | '/following'
    | '/friends'
    | '/help'
    | '/inbox'
    | '/live'
    | '/mcp'
    | '/music'
    | '/music-promotion-guide'
    | '/notifications'
    | '/offline'
    | '/profile'
    | '/qr'
    | '/report-problem'
    | '/rewards'
    | '/settings'
    | '/short-video-platform-for-musicians'
    | '/sitemap.xml'
    | '/stem'
    | '/studio'
    | '/trending'
    | '/verify'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/content'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/artist/onboarding'
    | '/artist/studio'
    | '/auth/callback'
    | '/help/chat'
    | '/help/safety'
    | '/inbox/$id'
    | '/live/$id'
    | '/posts/$id'
    | '/profile/edit'
    | '/profile/viewers'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/security'
    | '/story/$userId'
    | '/studio/$section'
    | '/u/$handle'
    | '/admin/'
    | '/settings/'
    | '/.mcp/invoke-tool/$tool'
    | '/settings/account/verification'
    | '/settings/security/recovery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  CreateRoute: typeof CreateRoute
  DiscoverRoute: typeof DiscoverRoute
  DramaRoute: typeof DramaRoute
  FeaturesRoute: typeof FeaturesRoute
  FollowersRoute: typeof FollowersRoute
  FollowingRoute: typeof FollowingRoute
  FriendsRoute: typeof FriendsRoute
  HelpRoute: typeof HelpRouteWithChildren
  InboxRoute: typeof InboxRouteWithChildren
  LiveRoute: typeof LiveRouteWithChildren
  McpRoute: typeof McpRoute
  MusicRoute: typeof MusicRoute
  MusicPromotionGuideRoute: typeof MusicPromotionGuideRoute
  NotificationsRoute: typeof NotificationsRoute
  OfflineRoute: typeof OfflineRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  QrRoute: typeof QrRoute
  ReportProblemRoute: typeof ReportProblemRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ShortVideoPlatformForMusiciansRoute: typeof ShortVideoPlatformForMusiciansRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StemRoute: typeof StemRoute
  StudioRoute: typeof StudioRouteWithChildren
  TrendingRoute: typeof TrendingRoute
  VerifyRoute: typeof VerifyRoute
  WalletRoute: typeof WalletRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ArtistOnboardingRoute: typeof ArtistOnboardingRoute
  ArtistStudioRoute: typeof ArtistStudioRoute
  PostsIdRoute: typeof PostsIdRoute
  StoryUserIdRoute: typeof StoryUserIdRoute
  UHandleRoute: typeof UHandleRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drama': {
      id: '/drama'
      path: '/drama'
      fullPath: '/drama'
      preLoaderRoute: typeof DramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followers': {
      id: '/followers'
      path: '/followers'
      fullPath: '/followers'
      preLoaderRoute: typeof FollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-promotion-guide': {
      id: '/music-promotion-guide'
      path: '/music-promotion-guide'
      fullPath: '/music-promotion-guide'
      preLoaderRoute: typeof MusicPromotionGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-problem': {
      id: '/report-problem'
      path: '/report-problem'
      fullPath: '/report-problem'
      preLoaderRoute: typeof ReportProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short-video-platform-for-musicians': {
      id: '/short-video-platform-for-musicians'
      path: '/short-video-platform-for-musicians'
      fullPath: '/short-video-platform-for-musicians'
      preLoaderRoute: typeof ShortVideoPlatformForMusiciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stem': {
      id: '/stem'
      path: '/stem'
      fullPath: '/stem'
      preLoaderRoute: typeof StemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/artist/onboarding': {
      id: '/artist/onboarding'
      path: '/artist/onboarding'
      fullPath: '/artist/onboarding'
      preLoaderRoute: typeof ArtistOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/studio': {
      id: '/artist/studio'
      path: '/artist/studio'
      fullPath: '/artist/studio'
      preLoaderRoute: typeof ArtistStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/help/chat': {
      id: '/help/chat'
      path: '/chat'
      fullPath: '/help/chat'
      preLoaderRoute: typeof HelpChatRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/safety': {
      id: '/help/safety'
      path: '/safety'
      fullPath: '/help/safety'
      preLoaderRoute: typeof HelpSafetyRouteImport
      parentRoute: typeof HelpRoute
    }
    '/inbox/$id': {
      id: '/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof InboxIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof LiveRoute
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/viewers': {
      id: '/profile/viewers'
      path: '/viewers'
      fullPath: '/profile/viewers'
      preLoaderRoute: typeof ProfileViewersRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/story/$userId': {
      id: '/story/$userId'
      path: '/story/$userId'
      fullPath: '/story/$userId'
      preLoaderRoute: typeof StoryUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$section': {
      id: '/studio/$section'
      path: '/$section'
      fullPath: '/studio/$section'
      preLoaderRoute: typeof StudioSectionRouteImport
      parentRoute: typeof StudioRoute
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account/verification': {
      id: '/settings/account/verification'
      path: '/verification'
      fullPath: '/settings/account/verification'
      preLoaderRoute: typeof SettingsAccountVerificationRouteImport
      parentRoute: typeof SettingsAccountRoute
    }
    '/settings/security/recovery': {
      id: '/settings/security/recovery'
      path: '/recovery'
      fullPath: '/settings/security/recovery'
      preLoaderRoute: typeof SettingsSecurityRecoveryRouteImport
      parentRoute: typeof SettingsSecurityRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface HelpRouteChildren {
  HelpChatRoute: typeof HelpChatRoute
  HelpSafetyRoute: typeof HelpSafetyRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpChatRoute: HelpChatRoute,
  HelpSafetyRoute: HelpSafetyRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface InboxRouteChildren {
  InboxIdRoute: typeof InboxIdRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxIdRoute: InboxIdRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

interface LiveRouteChildren {
  LiveIdRoute: typeof LiveIdRoute
}

const LiveRouteChildren: LiveRouteChildren = {
  LiveIdRoute: LiveIdRoute,
}

const LiveRouteWithChildren = LiveRoute._addFileChildren(LiveRouteChildren)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileViewersRoute: typeof ProfileViewersRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
  ProfileViewersRoute: ProfileViewersRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface SettingsAccountRouteChildren {
  SettingsAccountVerificationRoute: typeof SettingsAccountVerificationRoute
}

const SettingsAccountRouteChildren: SettingsAccountRouteChildren = {
  SettingsAccountVerificationRoute: SettingsAccountVerificationRoute,
}

const SettingsAccountRouteWithChildren = SettingsAccountRoute._addFileChildren(
  SettingsAccountRouteChildren,
)

interface SettingsSecurityRouteChildren {
  SettingsSecurityRecoveryRoute: typeof SettingsSecurityRecoveryRoute
}

const SettingsSecurityRouteChildren: SettingsSecurityRouteChildren = {
  SettingsSecurityRecoveryRoute: SettingsSecurityRecoveryRoute,
}

const SettingsSecurityRouteWithChildren =
  SettingsSecurityRoute._addFileChildren(SettingsSecurityRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRouteWithChildren
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsSecurityRoute: typeof SettingsSecurityRouteWithChildren
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRouteWithChildren,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsSecurityRoute: SettingsSecurityRouteWithChildren,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface StudioRouteChildren {
  StudioSectionRoute: typeof StudioSectionRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioSectionRoute: StudioSectionRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CommunityRoute: CommunityRoute,
  CreateRoute: CreateRoute,
  DiscoverRoute: DiscoverRoute,
  DramaRoute: DramaRoute,
  FeaturesRoute: FeaturesRoute,
  FollowersRoute: FollowersRoute,
  FollowingRoute: FollowingRoute,
  FriendsRoute: FriendsRoute,
  HelpRoute: HelpRouteWithChildren,
  InboxRoute: InboxRouteWithChildren,
  LiveRoute: LiveRouteWithChildren,
  McpRoute: McpRoute,
  MusicRoute: MusicRoute,
  MusicPromotionGuideRoute: MusicPromotionGuideRoute,
  NotificationsRoute: NotificationsRoute,
  OfflineRoute: OfflineRoute,
  ProfileRoute: ProfileRouteWithChildren,
  QrRoute: QrRoute,
  ReportProblemRoute: ReportProblemRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ShortVideoPlatformForMusiciansRoute: ShortVideoPlatformForMusiciansRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StemRoute: StemRoute,
  StudioRoute: StudioRouteWithChildren,
  TrendingRoute: TrendingRoute,
  VerifyRoute: VerifyRoute,
  WalletRoute: WalletRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ArtistOnboardingRoute: ArtistOnboardingRoute,
  ArtistStudioRoute: ArtistStudioRoute,
  PostsIdRoute: PostsIdRoute,
  StoryUserIdRoute: StoryUserIdRoute,
  UHandleRoute: UHandleRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
