/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as FollowersRouteImport } from './routes/followers'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as InboxIdRouteImport } from './routes/inbox.$id'
import { Route as HelpChatRouteImport } from './routes/help.chat'
import { Route as ArtistStudioRouteImport } from './routes/artist.studio'
import { Route as ArtistOnboardingRouteImport } from './routes/artist.onboarding'
import { Route as AdminVerificationsRouteImport } from './routes/admin/verifications'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRevenueRouteImport } from './routes/admin/revenue'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPayoutsRouteImport } from './routes/admin/payouts'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as SettingsAccountVerificationRouteImport } from './routes/settings.account.verification'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowersRoute = FollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIdRoute = InboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InboxRoute,
} as any)
const HelpChatRoute = HelpChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => HelpRoute,
} as any)
const ArtistStudioRoute = ArtistStudioRouteImport.update({
  id: '/artist/studio',
  path: '/artist/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistOnboardingRoute = ArtistOnboardingRouteImport.update({
  id: '/artist/onboarding',
  path: '/artist/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const SettingsAccountVerificationRoute =
  SettingsAccountVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => SettingsAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/followers': typeof FollowersRoute
  '/following': typeof FollowingRoute
  '/help': typeof HelpRouteWithChildren
  '/inbox': typeof InboxRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/artist/onboarding': typeof ArtistOnboardingRoute
  '/artist/studio': typeof ArtistStudioRoute
  '/help/chat': typeof HelpChatRoute
  '/inbox/$id': typeof InboxIdRoute
  '/live/$id': typeof LiveIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/settings/account': typeof SettingsAccountRouteWithChildren
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/u/$handle': typeof UHandleRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/account/verification': typeof SettingsAccountVerificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/followers': typeof FollowersRoute
  '/following': typeof FollowingRoute
  '/help': typeof HelpRouteWithChildren
  '/inbox': typeof InboxRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/artist/onboarding': typeof ArtistOnboardingRoute
  '/artist/studio': typeof ArtistStudioRoute
  '/help/chat': typeof HelpChatRoute
  '/inbox/$id': typeof InboxIdRoute
  '/live/$id': typeof LiveIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/settings/account': typeof SettingsAccountRouteWithChildren
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/u/$handle': typeof UHandleRoute
  '/admin': typeof AdminIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/account/verification': typeof SettingsAccountVerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/followers': typeof FollowersRoute
  '/following': typeof FollowingRoute
  '/help': typeof HelpRouteWithChildren
  '/inbox': typeof InboxRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/artist/onboarding': typeof ArtistOnboardingRoute
  '/artist/studio': typeof ArtistStudioRoute
  '/help/chat': typeof HelpChatRoute
  '/inbox/$id': typeof InboxIdRoute
  '/live/$id': typeof LiveIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/settings/account': typeof SettingsAccountRouteWithChildren
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/u/$handle': typeof UHandleRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/account/verification': typeof SettingsAccountVerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/create'
    | '/discover'
    | '/followers'
    | '/following'
    | '/help'
    | '/inbox'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/sitemap.xml'
    | '/verify'
    | '/wallet'
    | '/admin/content'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/artist/onboarding'
    | '/artist/studio'
    | '/help/chat'
    | '/inbox/$id'
    | '/live/$id'
    | '/profile/edit'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/u/$handle'
    | '/admin/'
    | '/settings/'
    | '/settings/account/verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create'
    | '/discover'
    | '/followers'
    | '/following'
    | '/help'
    | '/inbox'
    | '/notifications'
    | '/profile'
    | '/sitemap.xml'
    | '/verify'
    | '/wallet'
    | '/admin/content'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/artist/onboarding'
    | '/artist/studio'
    | '/help/chat'
    | '/inbox/$id'
    | '/live/$id'
    | '/profile/edit'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/u/$handle'
    | '/admin'
    | '/settings'
    | '/settings/account/verification'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/create'
    | '/discover'
    | '/followers'
    | '/following'
    | '/help'
    | '/inbox'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/sitemap.xml'
    | '/verify'
    | '/wallet'
    | '/admin/content'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/artist/onboarding'
    | '/artist/studio'
    | '/help/chat'
    | '/inbox/$id'
    | '/live/$id'
    | '/profile/edit'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/u/$handle'
    | '/admin/'
    | '/settings/'
    | '/settings/account/verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  DiscoverRoute: typeof DiscoverRoute
  FollowersRoute: typeof FollowersRoute
  FollowingRoute: typeof FollowingRoute
  HelpRoute: typeof HelpRouteWithChildren
  InboxRoute: typeof InboxRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyRoute: typeof VerifyRoute
  WalletRoute: typeof WalletRoute
  ArtistOnboardingRoute: typeof ArtistOnboardingRoute
  ArtistStudioRoute: typeof ArtistStudioRoute
  LiveIdRoute: typeof LiveIdRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followers': {
      id: '/followers'
      path: '/followers'
      fullPath: '/followers'
      preLoaderRoute: typeof FollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$id': {
      id: '/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof InboxIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/help/chat': {
      id: '/help/chat'
      path: '/chat'
      fullPath: '/help/chat'
      preLoaderRoute: typeof HelpChatRouteImport
      parentRoute: typeof HelpRoute
    }
    '/artist/studio': {
      id: '/artist/studio'
      path: '/artist/studio'
      fullPath: '/artist/studio'
      preLoaderRoute: typeof ArtistStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/onboarding': {
      id: '/artist/onboarding'
      path: '/artist/onboarding'
      fullPath: '/artist/onboarding'
      preLoaderRoute: typeof ArtistOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/settings/account/verification': {
      id: '/settings/account/verification'
      path: '/verification'
      fullPath: '/settings/account/verification'
      preLoaderRoute: typeof SettingsAccountVerificationRouteImport
      parentRoute: typeof SettingsAccountRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HelpRouteChildren {
  HelpChatRoute: typeof HelpChatRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpChatRoute: HelpChatRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface InboxRouteChildren {
  InboxIdRoute: typeof InboxIdRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxIdRoute: InboxIdRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface SettingsAccountRouteChildren {
  SettingsAccountVerificationRoute: typeof SettingsAccountVerificationRoute
}

const SettingsAccountRouteChildren: SettingsAccountRouteChildren = {
  SettingsAccountVerificationRoute: SettingsAccountVerificationRoute,
}

const SettingsAccountRouteWithChildren = SettingsAccountRoute._addFileChildren(
  SettingsAccountRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRouteWithChildren
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRouteWithChildren,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  DiscoverRoute: DiscoverRoute,
  FollowersRoute: FollowersRoute,
  FollowingRoute: FollowingRoute,
  HelpRoute: HelpRouteWithChildren,
  InboxRoute: InboxRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyRoute: VerifyRoute,
  WalletRoute: WalletRoute,
  ArtistOnboardingRoute: ArtistOnboardingRoute,
  ArtistStudioRoute: ArtistStudioRoute,
  LiveIdRoute: LiveIdRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
